### PR TITLE
Fix: {\c} should reset the colour to the Style default

### PR DESCRIPTION
**Pull request by Connum**
This is not clearly stated in the linked specs, but it differed from the implementations I have encountered so far (Kodi & VLC Player). The command {\c} without any colour specified used to reset the primary colour to the one previously used in that Dialogue. However, it should reset to the Style Default for that Dialogue.

Now the rendering is the same as in Kodi and VLC Player.

### CODE REVIEW

**Comment by weizhenye** [comment]
Really thanks for your interesting in this project.

According to my experience, nowadays most ASS files are created by [Aegisub](http://www.aegisub.org/), which is using [xy-VSFilter](https://github.com/Cyberbeing/xy-VSFilter) and [libass](https://github.com/libass/libass) as its renderer, what subtitle makers see is given by Aegisub, so actually these two libraries become the spec. These two libraries treat `\c` as `\1c`, and I handled it so. https://github.com/weizhenye/ASS/blob/d05f9ab66392b776703e6cce170d00fc08b45403/src/parser/tags.js#L170-L175

BTW, these days I'm woking on this project and do something changing it a lot. Like separating the parse part to [ass-compiler](https://github.com/weizhenye/ass-compiler), refactoring it with ES2015, modern workflow and more tests. But it's still WIP. So I recommend you to use it until I release the first version to NPM.

**Comment by Connum** [comment]
Hi there,

thanks for getting back to me.

I also fall back to `\1c` from `\c` if no digit is given, as can be seen in line 502:
https://github.com/weizhenye/ASS/pull/3/commits/1376223a7f12aa8dc55dea416be10f7b9c5799b0#diff-86b02a8f94a9a89a0efbdc20d6665c01R502

But my fix actually handles the case when no colour value is given. I had some subtitle files where that was the case, and they display as intended in Kodi and VLC, but not with this ASS implementation. For example:
- Default colour is yellow (`&H0011DCDB`)
`Style: Dialogue2,Tahoma,65,&H0011DCDB,&H000000FF,&H1F000000,&HC7000000,0,0,0,0,100,100,0,0,1,2.8,3.4,2,120,120,30,1`
- Now let's take this line:
`Dialogue: 0,0:11:42.74,0:11:44.74,Dialogue2,Unknown,0000,0000,0000,,{\an4\pos(675,992)\c&Hdcdcdc&}Do you like it? {\c}Yes, I do!`
- The "Yes, I do!" Should be yellow again, and it is indeed in all the players I tested. But with the ASS JS, it just stayed white before my fix.
- With my fix implemented, it does indeed change back to yellow

I don't know how common it is that `{\c}` without a colour is used, but I think it wouldn't hurt supporting it. I can't imagine a case where this would break anything, because why would someone set `{\c}` at all if they didn't want the colour to change?

**Comment by Connum** [comment]
By the way, as you mentioned AegiSub, I just downloaded it and tried it out. The behaviour of the preview is the same as in Kodi , VLC and my fixed ASS.js. So the renderer in the current state of your repo is definitely off! :-)

**Comment by Connum** [comment]
I tried doing it inside `parseAnimatableTags()` at first, but didn't find a way to access the Style defaults from within there. Do we need to pass them along as a second argument? Or are they already available from `this` in a way?

**Comment by weizhenye** [comment]
As second argument. `parseAnimatableTags` is only used in this file.

**Comment by Connum** [comment]
Ok, I'm at it! :)

**Comment by Connum** [comment]
The PR is now updated. :)

**Comment by weizhenye** [comment]
Thanks for your work.

**Comment by Connum** [comment]
Thanks for _yours_, happy to contribute!

**Pull request merged**
